# Generated by Django 3.2.7 on 2021-10-09 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('entry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(default='noname', max_length=20)),
                ('infection', models.CharField(default='noinfection', max_length=300)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('medicine', models.CharField(default='nomedicine', max_length=300)),
                ('outcome', models.CharField(default='neutral', max_length=20)),
            ],
        ),
    ]
