# Generated by Django 3.2.7 on 2021-10-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydata',
            name='duration',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
